import type { AgentActivity } from "../../ports/index.js"
import type { AgentRole } from "../../types.js"

/**
 * Live agent-activity derivation from real server events (captured from a
 * live opencode v1.1.x run, 2026-09-08):
 *
 * - `session.tool.input.started` → `{ sessionID, name: "read" }`
 * - `session.tool.called`        → `{ sessionID, input: { command | filePath … } }`
 * - `session.reasoning.started`  → agent is thinking
 * - `session.text.started`       → agent is composing the reply
 * - `session.usage.updated`      → cumulative token burn
 *
 * Deliberately deterministic: the loader text is computed, not generated by
 * another model — a spinner must never wait on an LLM. (If generated phrasing
 * is ever wanted, wrap the callback at the CLI layer.)
 */

export interface ActivityTrackerOptions {
  /** Role for a sessionID, when this run owns it (live lookup — sessions appear during the run). */
  owned: (sessionID: string) => AgentRole | undefined
  /** Called when the activity view meaningfully changes (never per stream delta). */
  onActivity: (info: AgentActivity) => void
}

interface TrackedSession {
  role: AgentRole
  label: string
  tokens: number
  /** last rendered key — dedupes chatty events */
  rendered: string
}

export class ActivityTracker {
  private readonly sessions = new Map<string, TrackedSession>()

  constructor(private readonly opts: ActivityTrackerOptions) {}

  observe(raw: unknown): void {
    const ev = raw as Record<string, any>
    if (!ev || typeof ev !== "object") return
    const type: string | undefined = ev.type
    const data = ev.data
    if (!type || !data || typeof data !== "object") return
    const sessionID: string | undefined = data.sessionID
    if (!sessionID) return
    const role = this.opts.owned(sessionID)
    if (!role) return // server-global stream — foreign sessions are ignored

    const tracked = this.sessions.get(sessionID) ?? { role, label: "working", tokens: 0, rendered: "" }

    if (type === "session.tool.input.started" && typeof data.name === "string") {
      tracked.label = data.name
    } else if (type === "session.tool.called" && data.input && typeof data.input === "object") {
      const detail = toolDetail(data.input)
      if (detail) tracked.label = detail
    } else if (type === "session.reasoning.started") {
      tracked.label = "thinking"
    } else if (type === "session.text.started") {
      tracked.label = "composing"
    } else if (type === "session.usage.updated" && data.tokens && typeof data.tokens === "object") {
      const t = data.tokens
      tracked.tokens +=
        numberOr(t.input) + numberOr(t.output) + numberOr(t.reasoning) + numberOr(t.cache?.read) + numberOr(t.cache?.write)
    } else {
      return
    }

    const rendered = `${tracked.label}#${Math.floor(tracked.tokens / 1000)}`
    if (rendered === tracked.rendered) return // throttle: only meaningful changes
    tracked.rendered = rendered
    this.sessions.set(sessionID, tracked)
    this.opts.onActivity({ role, text: tracked.label, tokens: tracked.tokens })
  }
}

/** Short, human detail from tool arguments: a path, or a clipped command. */
function toolDetail(input: Record<string, any>): string | undefined {
  const tool: string | undefined = typeof input.tool === "string" ? input.tool : undefined
  const filePath: string | undefined =
    [input.filePath, input.path, input.file].find((v): v is string => typeof v === "string")
  const command: string | undefined = typeof input.command === "string" ? input.command : undefined
  if (filePath) return `${tool ? `${tool} ` : ""}${filePath}`
  if (command) return `${tool ? `${tool} ` : ""}${command.slice(0, 48)}${command.length > 48 ? "…" : ""}`
  return tool
}

function numberOr(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value : 0
}
